### ISSUE TITLE
Support for Microsoft.Extensions.Configuration

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-dotnet#2]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration?view=aspnetcore-2.0

EnvKey could be a configuration provider so that the environment variables aren't overwritten yet the configuration is composable.

**Comment by dbeattie71** [comment]
I created one based on AzureAppConfiguration:
https://github.com/bytefoo/extensions-configuration-envkey
https://www.nuget.org/packages/ByteFoo.Extensions.Configuration.EnvKey
