### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by danenania** [envkey/envkey-dotnet#4]
Hey @SeriousM, we have a potential customer who would like to use this package but needs Mac support. Do you have a sense of what it would take to get this added? I see that the binaries for windows/linux are pulled down in `NuGet/download_envkey.bat`--is it just a matter of adding the darwin binary here and rebuilding? Thanks!

**Comment by SeriousM** [comment]
Technically yes, but the package would get another 50% heavier which results from current 6.51mb to approx. ~9mb.
I would raise an issue with a poll instead adding everyone so much more binary size.
Just to be clear: the additional 3mb counts towards the resulting binary package.

**Comment by danenania** [comment]
Ok, my choice for the main package would be to include the darwin binary despite the extra file size since now there's a user with a need for it--this has not been an issue for users of other packages despite having even more binaries (for 32 bit as well) included.

I understand the concern though, so the plan for all packages across the board is to keep all binaries in the default packages for maximum compatibility, then create platform-specific packages for cases where file size is a concern. So in this case, we can have the build script produce and upload two packages: `envkey-dotnet` with binaries for all three platforms, and then `envkey-dotnet-windows` which will include only the windows binary.

I know we have discussed it before and I respect that you might have a different opinion and not want to go in this direction, but from a business perspective we need to have cross-platform support from all official packages since this is an important goal of the product and is the expectation new users get from our marketing. So if you disagree and would rather not add support that's fine, but then I would take over as maintainer in order to get this done. I hope that makes sense--I really do appreciate all the work you've put into this!

**Comment by SeriousM** [comment]
This is perfectly fine with me, a split of packages was the way to go for
me and the package is actually designed to splitable.
Offering a all-in-one and separate packages just adds value options for the
users.
I will prepare all the necessary steps and stay the maintainer as you
wouldn't have the necessary dotnet experience, no offense :)

**Comment by danenania** [comment]
Haha you are absolutely right about that. I much prefer that you remain the maintainer--I just didn't want to push you to do something you disagree with but that is needed from the business perspective, given that you're a volunteer :) But I'm glad to hear you agree on the split packages approach!

**Comment by SeriousM** [comment]
Hi @danenania, I have already a plan how we will progress with the nuget packages.
Unfortunately it will be a bit different as what we wanted to do.

The plan is to have one base package eg. EnvKey.Sdk and for each Platform one Package like EnvKey.Win,  EnvKey.Linux and EnvKey.Osx. Maybe I can create another package like EnvKey.AllPlatforms but I have to check if it would interfere with the others in case Win and AllPlatforms is installed at the same time.
Anyway, the Platform packages will demand on EnvKey.Sdk.
Does that sounds good to you?

We could cover the cases:
- All in: User only requires EnvKey.AllPlatforms and can be happy.
- Selected Palatforms: User only requires Linux and Win and can save some bytes.

Cheers

**Comment by danenania** [comment]
Hi @SeriousM! This approach sounds good to me. I do think we need the all-platforms package. It would be fine if it breaks or throws an error if multiple packages are included. We'll just have to make it clear in the docs.

I'd also like to name the 'all-platforms' package `EnvKey` instead of `EnvKey.AllPlatforms` so that it's clear this is the default package and the name is easy to remember.

Other than that, sounds perfect! Thanks!

**Comment by SeriousM** [comment]
Alright, done! The full package is packed around 10mb, extracted around 28mb.
All packages around envkey can be found via https://www.nuget.org/packages?q=Tags%3A%22envkey%22 (which you should use on the docs)
