### ISSUE TITLE
Documentation updates: .env question

### ISSUE THREAD

**Issue by danenania** [envkey/envkey-dotnet#5]
Hey @SeriousM, I'm working on beefing up the documentation to make it consistent with others, and had a question: is the package attempting to load a `.env` file from the project root before executing the envkey binary? I didn't see this in a quick scan of the code, so I wanted to check. 

If not, could we add this step, perhaps with a package like [this one](https://github.com/tonerdo/dotnet-env) for the sake of consistency?

**Comment by SeriousM** [comment]
Hey Dane!

The package doesn't do that by itself.
We could add the functionality but not right now as this needs some deeper
thoughts about where to find the .env file.
In dotnet we don't always know where the codebase lies and this needs a
understandable interface to the user.

Tahnk you for your work!

**Comment by SeriousM** [comment]
Btw, the package supports windows (x64) as well as linux.

**Comment by danenania** [comment]
Ok thanks. There was a similar issue of determining project root in envkey-python, which was solved with a `os.getcwd()` call, which gives whatever directory the current process is started from.

From [this SO thread](https://stackoverflow.com/questions/21726088/how-to-get-current-working-directory-path-c) it seems that either `System.IO.Directory.GetCurrentDirectory();` or `System.IO.Path.GetDirectoryName(System.Windows.Forms.Application.ExecutablePath);` could have potential?

**Comment by SeriousM** [comment]
The point here is that dotnet can not only be executed as standard
executable but as windows service, in iis as embedded executable or as web
application, as Azure function, with the help of the dotnet runtime and
other wonderful ways.
I want to find an easy way to let the user choose which environment is
currently executed. A simple SO check is not enough here.

**Comment by danenania** [comment]
I see, but in these situations where there is no simple concept of a 'root directory' then it's fine if we just don't find a `.env`, since we'll still check for the `ENVKEY` environment variable as you're already doing. The main use of the `.env` is in development, so as long it would find the `.env` file in most common development use cases, that would be sufficient.
