### ISSUE TITLE
Hide envkey binaries in solution explorer

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-dotnet#7]
![image](https://user-images.githubusercontent.com/462013/54986439-eec26100-4fb2-11e9-8c3c-92edfcaf5950.png)

We can hide the binaries from the solution explorer by adding a props file to the nuget folder:

The testadapter from microsoft does this already:

https://github.com/Microsoft/testfx/blob/master/src/Package/MSTest.TestAdapter.nuspec
```
...
<file src="Build\NetCore\MSTest.TestAdapter.props" target="build\netcoreapp1.0\" />
...
```

https://github.com/Microsoft/testfx/blob/master/src/Adapter/Build/NetCore/MSTest.TestAdapter.props
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)..\_common\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll">
      <Link>Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by danenania** [comment]
@SeriousM Yeah, it would definitely be nice to hide those! It sounds like a good idea and good approach to me.

**Comment by SeriousM** [comment]
I've invested some time into it but didn't managed to hide the files. I would have to rewrite the nuget nuspec-files and structure, and I would have to sacrifice the full notnet framework support (net472). Therefore I would stick with the visible files. It's ok to have them and it's also a good indicator that the project is actually referencing the binaries instead only the sdk.

**Comment by danenania** [comment]
Ok, that makes sense—sounds good!
