### ISSUE TITLE
Envkey v2 support

### ISSUE THREAD

**Issue by dbsanfte** [envkey/envkey-dotnet#9]
Will this library be updated for Envkey 2?

**Comment by SeriousM** [comment]
Hi David, yes, it will get an update soon. I will update this issue once it's done. The api will not be that different though.

**Comment by SeriousM** [comment]
David, I just published a nuget package that targets the version `2.0.27`. Would you please tell me if you have any issues with it? My tests with various frameworks works well.

**Comment by dbsanfte** [comment]
@freek-hoekstra-cardano 

Freek would you mind having a go at testing this package in a C# project?

cc: @chookie

**Comment by SeriousM** [comment]
Closing this as version 2 is now supported for months.
